In [32]:
#bisection Method

In [33]:
import numpy as np

In [34]:
# function 
# 2x+y+z=10
#3x+2y+3z=18
#x+4y+9z=16

In [35]:
a=np.array([[2,1,1],[3,2,3],[1,4,9]],float)
b=np.array([[10],[18],[16]],float)

In [36]:
print(a)

[[2. 1. 1.]
 [3. 2. 3.]
 [1. 4. 9.]]


In [37]:
print(b)

[[10.]
 [18.]
 [16.]]


In [38]:
n=len(b)
print(n)

3


In [39]:
for i in range(0,n-1):
    m1=a[i,i]
    print("m1 us",m1)
    a[i,:]=a[i,:]/m1
    b[i]=b[i]/m1
    print(a,",")
    for j in range(i+1,n):
        m2=a[j,i]
        print("m2 is:",m2)
        a[j,:]-=m2*a[i,:]
        b[j]=b[j]-m2*b[i]
        print(a,",")
print("Matrix after gaussian elimination is:")
print(a)


m1 us 2.0
[[1.  0.5 0.5]
 [3.  2.  3. ]
 [1.  4.  9. ]] ,
m2 is: 3.0
[[1.  0.5 0.5]
 [0.  0.5 1.5]
 [1.  4.  9. ]] ,
m2 is: 1.0
[[1.  0.5 0.5]
 [0.  0.5 1.5]
 [0.  3.5 8.5]] ,
m1 us 0.5
[[1.  0.5 0.5]
 [0.  1.  3. ]
 [0.  3.5 8.5]] ,
m2 is: 3.5
[[ 1.   0.5  0.5]
 [ 0.   1.   3. ]
 [ 0.   0.  -2. ]] ,
Matrix after gaussian elimination is:
[[ 1.   0.5  0.5]
 [ 0.   1.   3. ]
 [ 0.   0.  -2. ]]


In [40]:
print(b)

[[  5.]
 [  6.]
 [-10.]]


In [41]:
n=len(b)
x=np.zeros(n)
print(x)
for i in range(n-1,-1,-1):
    x[i]=b[i]
    print(x,",")
    for j in range (i+1,n):
        x[i]=x[i]-a[i,j]*x[j]
    x[i]=x[i]/a[i,i]
    print(x,",")

print("Solution Vector x: ")
print(x)

[0. 0. 0.]
[  0.   0. -10.] ,
[0. 0. 5.] ,
[0. 6. 5.] ,
[ 0. -9.  5.] ,
[ 5. -9.  5.] ,
[ 7. -9.  5.] ,
Solution Vector x: 
[ 7. -9.  5.]


C:\Users\user\AppData\Local\Temp\ipykernel_24544\1834481435.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[i]=b[i]
